# Tehnologija upravljanja podatkov
# Luka.Sajn@fri.uni-lj.si
# Windows, Power designer 12.5, Java JDK, Python 3, dotnet6 SDK, Jupyter Notebook, Eclipse, MySql Workbench, MySQL ODBC Connector, Notepad++
dependencies:
  - role: eclipse
  - role: dotnet6
  - role: jupyter
  - role: jdk
  - role: powerdesigner
  - role: mysql_workbench
  - role: mysql-odbc-connector
  - role: notepad++

