VSCode_Extensions:
  - VisualStudioExptTeam.vscodeintellicode
  - arthurwang.vsc-prolog
  - dramforever.vscode-ghc-simple
  - eamodio.gitlens
  - justusadam.language-haskell
  - ms-dotnettools.csdevkit # IS-63714
  - ms-python.python
  - ms-vscode.cpptools
  - ocamllabs.ocaml-platform
  - stonebuddha.vscode-better-sml
  - vscode-icons-team.vscode-icons
  - vscjava.vscode-java-pack
  - dan-c-underwood.arm # RA-63703
  - marus25.cortex-debug # RA-63703
  - NateAGeek.memory-viewer # RA-63703
  - ms-vscode.cpptools-extension-pack # RA-63703
  - platformio.platformio-ide # ORS-63218
  - stmicroelectronics.stm32-vscode-extension # RA-63703
