dependencies:
  - role: fri_base
  - role: AAHRP-63263
  - role: APS1-63279
  - role: ARP1-63545C
  - role: BMO-63259
  - role: DF-63530
  - role: DN-63260
  - role: DPS-63744
  - role: DV-63718
  - role: EP-63249
  - role: FP-63507
  - role: GO-63715
  - role: IS-63714
  - role: IVZ-63521
  - role: KCR-63550
  - role: KPOV-63716
  - role: KRV-63528
  - role: MRO-63257
  - role: MV-63288
  - role: NDN-63729
  - role: NM-63522
  - role: NPMP-63512
  - role: NRG-63553
  - role: OBSS-63514
  - role: ODV-63204
  - role: OO-63271
  - role: OR-63717
  - role: ORS-63218
  - role: OS-63709
  - role: OS-63741
  - role: OUI-63214
  - role: P2-63278
  - role: P2-63706
  - role: PA-63737
  - role: PB2-63713
  - role: PB-63707
  - role: PJC-63769
  - role: PPJ-63220
  - role: PS-63261
  - role: PSP-63287
  - role: PUI-63768
  - role: RA-63703
  - role: RGTI-63269
  - role: RIS-63252
  - role: RK-63209
  - role: RK-63708
  - role: RPOI-90066
  - role: RZP-63523
  - role: SP-63255
  - role: ST-63727
  - role: SU-63519
  - role: TINR-63740
  - role: TIS-63216
  - role: TUP-63226
  - role: UI-63720
  - role: UV-63721
  - role: UZ-63267
  - role: VN-63728
  - role: VP-63775
  - role: VPSA-63735
  - role: VZR-63543
